name: demo-actions

on: 
  push:
    branches: 
      - main  # Runs on push to the 'main' branch

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v4  # Fetches latest code

      - name: Run a Sample Command
        run: echo "Hello, World!"  # Executes a command in shell

      - name: Upload Artifact
        uses: actions/upload-artifact@v4  # Uploads build files
        with:
          name: build-artifact  # Artifact name
          path: ${{ github.workspace }}  # Corrected variable

  deploy:
    runs-on: ubuntu-latest

    steps: 
      - name: Download Artifact
        uses: actions/download-artifact@v4  # Correct action name
        with: 
          name: build-artifact
          path: ${{ github.workspace }}  # Corrected variable

      - name: Deploy Step
        run: echo "Deploying application..."  # Simulate deployment process
